## Observations and Insights

In [5]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st

# Study data files
mouse_metadata_path = "data/Mouse_metadata.csv"
study_results_path = "data/Study_results.csv"

# Read the mouse data and the study results
mouse_metadata = pd.read_csv(mouse_metadata_path)
study_results = pd.read_csv(study_results_path)

# Combine the data into a single dataset
merge_df = pd.merge(mouse_metadata, study_results)
# Display the data table for preview
merge_df.head()

,Mouse ID,Drug Regimen,Sex,Age_months,Weight (g),Timepoint,Tumour Volume (mm3),Metastatic Sites
0,k403,Ramicane,Male,21,16,0,45.000000,0
1,k403,Ramicane,Male,21,16,5,38.825898,0
2,k403,Ramicane,Male,21,16,10,35.014271,1
3,k403,Ramicane,Male,21,16,15,34.223992,1
4,k403,Ramicane,Male,21,16,20,32.997729,1

In [6]:
#Getting number of mice
unique_mice = merge_df['Mouse ID'].unique()
len(unique_mice)

249

In [7]:
duplicated = merge_df.duplicated()
print(duplicated)

0       False
1       False
2       False
3       False
4       False
        ...
1888    False
1889    False
1890    False
1891    False
1892    False
Length: 1893, dtype: bool

In [8]:
# Getting the duplicate mice by ID number that shows up for Mouse ID and Timepoint. 
merge_df.loc[merge_df.duplicated(), :]

,Mouse ID,Drug Regimen,Sex,Age_months,Weight (g),Timepoint,Tumour Volume (mm3),Metastatic Sites
909,g989,Propriva,Female,21,26,0,45.0,0

In [9]:
new_df = merge_df.drop_duplicates()
len(new_df)

1892

In [72]:
print(new_df)

     Mouse ID Drug Regimen   Sex  Age_months  Weight (g)  Timepoint  \
0        k403     Ramicane  Male          21          16          0
1        k403     Ramicane  Male          21          16          5
2        k403     Ramicane  Male          21          16         10
3        k403     Ramicane  Male          21          16         15
4        k403     Ramicane  Male          21          16         20
...       ...          ...   ...         ...         ...        ...
1888     z969     Naftisol  Male           9          30         25
1889     z969     Naftisol  Male           9          30         30
1890     z969     Naftisol  Male           9          30         35
1891     z969     Naftisol  Male           9          30         40
1892     z969     Naftisol  Male           9          30         45

      Tumour Volume (mm3)  Metastatic Sites
0               45.000000                 0
1               38.825898                 0
2               35.014271                 1
3               34.223992                 1
4               32.997729                 1
...                   ...               ...
1888            63.145652                 2
1889            65.841013                 3
1890            69.176246                 4
1891            70.314904                 4
1892            73.867845                 4

[1892 rows x 8 columns]

In [10]:
# Getting the duplicate mice by ID number that shows up for Mouse ID and Timepoint. 
#test_df = merge_df[['Mouse ID', 'Timepoint']]
#print(test_df)

In [4]:
# Optional: Get all the data for the duplicate mouse ID.

In [5]:
# Create a clean DataFrame by dropping the duplicate mouse by its ID.

In [6]:
# Checking the number of mice in the clean DataFrame.

In [23]:
regimen = merge_df['Drug Regimen'].unique()
print(regimen)

['Ramicane' 'Capomulin' 'Infubinol' 'Placebo' 'Ceftamin' 'Stelasyn'
 'Zoniferol' 'Ketapril' 'Propriva' 'Naftisol']

## Summary Statistics

In [43]:
#Rami_df = new_df['Drug Regimen'] == "Ramicane"
#print(Rami_df)

Rami_df = new_df[new_df['Drug Regimen'].str.contains('Ramicane')]
Capo_df = new_df[new_df['Drug Regimen'].str.contains('Capomulin')]
Infu_df = new_df[new_df['Drug Regimen'].str.contains('Infubinol')]
Plac_df = new_df[new_df['Drug Regimen'].str.contains('Placebo')]
Ceft_df = new_df[new_df['Drug Regimen'].str.contains('Ceftamin')]
Stela_df = new_df[new_df['Drug Regimen'].str.contains('Stelasyn')]
Zoni_df = new_df[new_df['Drug Regimen'].str.contains('Zoniferol')]
Keta_df = new_df[new_df['Drug Regimen'].str.contains('Ketapril')]
Prop_df = new_df[new_df['Drug Regimen'].str.contains('Propriva')]
Naft_df = new_df[new_df['Drug Regimen'].str.contains('Naftisol')]

     Mouse ID Drug Regimen     Sex  Age_months  Weight (g)  Timepoint  \
558      a818     Naftisol  Female          12          28          0
559      a818     Naftisol  Female          12          28          5
560      a818     Naftisol  Female          12          28         10
561      a818     Naftisol  Female          12          28         15
562      a818     Naftisol  Female          12          28         20
...       ...          ...     ...         ...         ...        ...
1888     z969     Naftisol    Male           9          30         25
1889     z969     Naftisol    Male           9          30         30
1890     z969     Naftisol    Male           9          30         35
1891     z969     Naftisol    Male           9          30         40
1892     z969     Naftisol    Male           9          30         45

      Tumour Volume (mm3)  Metastatic Sites
558             45.000000                 0
559             45.696709                 0
560             49.790919                 0
561             51.227566                 0
562             54.834624                 0
...                   ...               ...
1888            63.145652                 2
1889            65.841013                 3
1890            69.176246                 4
1891            70.314904                 4
1892            73.867845                 4

[186 rows x 8 columns]

In [48]:
# Generate a summary statistics table of mean, median, variance, standard deviation, and SEM of the tumour volume for each regimen
Rami_mean = Rami_df["Tumour Volume (mm3)"].mean()
Rami_median = Rami_df["Tumour Volume (mm3)"].median()
Rami_var = Rami_df["Tumour Volume (mm3)"].var()
Rami_std = Rami_df["Tumour Volume (mm3)"].std()
Rami_sem = Rami_df["Tumour Volume (mm3)"].sem()

Capo_mean = Capo_df["Tumour Volume (mm3)"].mean()
Capo_median = Capo_df["Tumour Volume (mm3)"].median()
Capo_var = Capo_df["Tumour Volume (mm3)"].var()
Capo_std = Capo_df["Tumour Volume (mm3)"].std()
Capo_sem = Capo_df["Tumour Volume (mm3)"].sem()

Infu_mean = Infu_df["Tumour Volume (mm3)"].mean()
Infu_median = Infu_df["Tumour Volume (mm3)"].median()
Infu_var = Infu_df["Tumour Volume (mm3)"].var()
Infu_std = Infu_df["Tumour Volume (mm3)"].std()
Infu_sem = Infu_df["Tumour Volume (mm3)"].sem()

Plac_mean = Plac_df["Tumour Volume (mm3)"].mean()
Plac_median = Plac_df["Tumour Volume (mm3)"].median()
Plac_var = Plac_df["Tumour Volume (mm3)"].var()
Plac_std = Plac_df["Tumour Volume (mm3)"].std()
Plac_sem = Plac_df["Tumour Volume (mm3)"].sem()

Ceft_mean = Ceft_df["Tumour Volume (mm3)"].mean()
Ceft_median = Ceft_df["Tumour Volume (mm3)"].median()
Ceft_var = Ceft_df["Tumour Volume (mm3)"].var()
Ceft_std = Ceft_df["Tumour Volume (mm3)"].std()
Ceft_sem = Ceft_df["Tumour Volume (mm3)"].sem()

Stela_mean = Stela_df["Tumour Volume (mm3)"].mean()
Stela_median = Stela_df["Tumour Volume (mm3)"].median()
Stela_var = Stela_df["Tumour Volume (mm3)"].var()
Stela_std = Stela_df["Tumour Volume (mm3)"].std()
Stela_sem = Stela_df["Tumour Volume (mm3)"].sem()

Zoni_mean = Zoni_df["Tumour Volume (mm3)"].mean()
Zoni_median = Zoni_df["Tumour Volume (mm3)"].median()
Zoni_var = Zoni_df["Tumour Volume (mm3)"].var()
Zoni_std = Zoni_df["Tumour Volume (mm3)"].std()
Zoni_sem = Zoni_df["Tumour Volume (mm3)"].sem()

Keta_mean = Keta_df["Tumour Volume (mm3)"].mean()
Keta_median = Keta_df["Tumour Volume (mm3)"].median()
Keta_var = Keta_df["Tumour Volume (mm3)"].var()
Keta_std = Keta_df["Tumour Volume (mm3)"].std()
Keta_sem = Keta_df["Tumour Volume (mm3)"].sem()

Prop_mean = Prop_df["Tumour Volume (mm3)"].mean()
Prop_median = Prop_df["Tumour Volume (mm3)"].median()
Prop_var = Prop_df["Tumour Volume (mm3)"].var()
Prop_std = Prop_df["Tumour Volume (mm3)"].std()
Prop_sem = Prop_df["Tumour Volume (mm3)"].sem()

Naft_mean = Naft_df["Tumour Volume (mm3)"].mean()
Naft_median = Naft_df["Tumour Volume (mm3)"].median()
Naft_var = Naft_df["Tumour Volume (mm3)"].var()
Naft_std = Naft_df["Tumour Volume (mm3)"].std()
Naft_sem = Naft_df["Tumour Volume (mm3)"].sem()

stats_df = pd.DataFrame(
    {"Mean" : [Rami_mean, Capo_mean, Infu_mean, Plac_mean, Ceft_mean, Stela_mean, Zoni_mean, Keta_mean, Prop_mean, Naft_mean],
    "Median" : [Rami_median, Capo_median, Infu_median, Plac_median, Ceft_median, Stela_median, Zoni_median, Keta_median, Prop_median, Naft_median],
    "Variance" : [Rami_var, Capo_var, Infu_var, Plac_var, Ceft_var, Stela_var, Zoni_var, Keta_var, Prop_var, Naft_var],
    "Standard Deviation" : [Rami_std, Capo_std, Infu_std, Plac_std, Ceft_std, Stela_std, Zoni_std, Keta_std, Prop_std, Naft_std],
    "SEM" : [Rami_sem, Capo_sem, Infu_sem, Plac_sem, Ceft_sem, Stela_sem, Zoni_sem, Keta_sem, Prop_sem, Naft_sem],},
    index = ["Ramicane", "Capomulin", "Infubinol", "Placebo", "Ceftamin", "Stelasyn", "Zonifero", "Ketapril", "Propriva", "Naftisol"])

print(stats_df)

# Use groupby and summary statistical methods to calculate the following properties of each drug regimen: 
# mean, median, variance, standard deviation, and SEM of the tumour volume. 
# Assemble the resulting series into a single summary dataframe.
# Generate a summary statistics table of mean, median, variance, standard deviation, and SEM of the tumour volume for each regimen

                Mean     Median   Variance  Standard Deviation       SEM
Ramicane   40.216745  40.673236  23.486704            4.846308  0.320955
Capomulin  40.675741  41.557809  24.947764            4.994774  0.329346
Infubinol  52.884795  51.820584  43.128684            6.567243  0.492236
Placebo    54.033581  52.288934  61.168083            7.821003  0.581331
Ceftamin   52.591172  51.776157  39.290177            6.268188  0.469821
Stelasyn   54.233149  52.431737  59.450562            7.710419  0.573111
Zonifero   53.236507  51.818479  48.533355            6.966589  0.516398
Ketapril   55.235638  53.698743  68.553577            8.279709  0.603860
Propriva   52.368318  50.909965  42.278090            6.502160  0.514041
Naftisol   54.331565  52.509285  66.173479            8.134708  0.596466

In [75]:
# Using the aggregation method, produce the same summary statistics in a single line
#print(stats_df.aggregate(['mean']))
print(new_df.groupby('Drug Regimen')['Tumour Volume (mm3)'].aggregate('mean'))
#print(Rami_df.aggregate(['mean']))

Drug Regimen
Capomulin    40.675741
Ceftamin     52.591172
Infubinol    52.884795
Ketapril     55.235638
Naftisol     54.331565
Placebo      54.033581
Propriva     52.368318
Ramicane     40.216745
Stelasyn     54.233149
Zoniferol    53.236507
Name: Tumour Volume (mm3), dtype: float64

## Bar and Pie Charts

In [9]:
# Generate a bar plot showing the total number of timepoints for all mice tested for each drug regimen using Pandas

In [10]:
# Generate a bar plot showing the total number of timepoints for all mice tested for each drug regimen using pyplot.

In [11]:
# Generate a pie plot showing the distribution of female versus male mice using Pandas

In [12]:
# Generate a pie plot showing the distribution of female versus male mice using pyplot

## Quartiles, Outliers and Boxplots

In [13]:
# Calculate the final tumor volume of each mouse across four of the treatment regimens:  
# Capomulin, Ramicane, Infubinol, and Ceftamin

# Start by getting the last (greatest) timepoint for each mouse


# Merge this group df with the original dataframe to get the tumour volume at the last timepoint

In [14]:
# Put treatments into a list for for loop (and later for plot labels)


# Create empty list to fill with tumour vol data (for plotting)


# Calculate the IQR and quantitatively determine if there are any potential outliers. 

    
    # Locate the rows which contain mice on each drug and get the tumour volumes
    
    
    # add subset 
    
    
    # Determine outliers using upper and lower bounds

In [15]:
# Generate a box plot of the final tumour volume of each mouse across four regimens of interest

## Line and Scatter Plots

In [16]:
# Generate a line plot of tumour volume vs. time point for a mouse treated with Capomulin

In [17]:
# Generate a scatter plot of average tumour volume vs. mouse weight for the Capomulin regimen

## Correlation and Regression

In [18]:
# Calculate the correlation coefficient and linear regression model 
# for mouse weight and average tumour volume for the Capomulin regimen